```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
d<-unique(stud$Dept)
ar<-c()
for (x in d)
{
  temp<-c()
  print(paste("DEPT ",x))
  temp<-stud$Names[stud$Dept==x & (stud$SGPA>=8 )]
  print(temp)
  ar<-append(ar,length(temp))
}
print(ar)
plot(c(1:length(d)),ar,xlab='',xaxt='n')
axis(1, at=c(1:length(d)), labels=d, las=2)

```

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
r<-c(1:14)
S<-as.factor(c())
F<-c()#works without as.factor
for (i in r)
  {
 
  x <- stud[i,]

  if (x$M1 > 60||x$M2 > 60||x$M3 > 60||x$M4 > 60||x$M5 > 60)
    S<-append(S,as.character(x$Names))
  if (x$M1 < 50||x$M2 < 50||x$M3 < 50||x$M4 < 50||x$M5 < 50)
    F<-append(F,as.character(x$Names))
  
}
#S<-mapvalues(S,c(1:14),stud$Names)
print(paste("S GRADE",S))
print(paste("FAIL",F))
```

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
d<-unique(stud$Dept)
r<-c(1:14)
count=0
sum=0
for (j in c(1:length(d))){
  for (i in r){
    x<-stud[i,]
    if(x$Dept==d[j]){
      count=count+1
      sum=sum+x$SGPA
    }
  }
  print(paste(d[j],sum/count))
  sum=0
  count=0
}
```

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
d<-unique(stud$Dept)
r<-c(1:14)
count=0
sum1=0
sum2=0
sum3=0
sum4=0
sum5=0
for (j in c(1:length(d))){
  for (i in r){
    x<-stud[i,]
    if(x$Dept==d[j]){
      count=count+1
      sum1=sum1+x$M1
      sum2=sum2+x$M2
      sum3=sum3+x$M3
      sum4=sum4+x$M4
      sum5=sum5+x$M5
    }
  }
  print(d[j])
  print(paste("M1",sum1/count))
  print(paste("M2",sum2/count))
  print(paste("M3",sum3/count))
  print(paste("M4",sum4/count))
  print(paste("M5",sum5/count))
  sum1=0
sum2=0
sum3=0
sum4=0
sum5=0
  count=0
}
```

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
d<-unique(stud$Dept)
r<-c(1:14)
max=0
for (j in c(1:length(d))){
  for (i in r){
    x<-stud[i,]
    if(x$Dept==d[j]){
      if(x$SGPA>max){
        max=x$SGPA
        topper=x$Names
      }
    }
  }
  print(paste(d[j],topper))
  max=0
}
```

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
d<-unique(stud$Dept)
r<-c(1:14)
for (j in c(1:length(d))){
for (i in r){
    x<-stud[i,]
    df <- subset(stud,Dept==d[j], select = c("Names","USN","Dept","M1","M2","M3","M4","M5","SGPA"))
}
  print(df)
}
``` 

```{r}
stud<-read.csv("F:/7th sem/Clas/R/coll.csv")
attach(stud)
s<-stud[order(SGPA),]
print("order by sgpa")
print(s)
s<-stud[order(SGPA,M1),]
print("order by sgpa and M1")
print(s)
s<-stud[order(SGPA,-M1),]
print("order by sgpa(asc) and M1(desc")
print(s)
```

```{r}

r<-c(1:14)
c<-c(1:9)
for(i in r){
  for(j in c){
    if(stud[i,j]=="H")
      print(stud[i,])
  }
}
```